### ISSUE TITLE
Cannot use, properly installed already still not working

### ISSUE THREAD

**Issue by El-Poyo-Loco** [beagle-dev/beagle-lib#118]
java.lang.RuntimeException: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
	at beagle.BeagleFactory.loadBeagleInstance(Unknown Source)
	at dr.app.beagle.evomodel.treelikelihood.BeagleTreeLikelihood.<init>(Unknown Source)
	at dr.app.beagle.evomodel.parsers.BeagleTreeLikelihoodParser.createTreeLikelihood(Unknown Source)
	at dr.app.beagle.evomodel.parsers.BeagleTreeLikelihoodParser.parseXMLObject(Unknown Source)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
java.lang.
BEAST has terminated with an error. Please select QUIT from the menu.
RuntimeException: Terminate
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)

**Comment by El-Poyo-Loco** [comment]
Im new to github, not sure if this is the proper way to ask for help with the program.
