### ISSUE TITLE
Mac binary installer version fails with OpenJDKs

### ISSUE THREAD

**Issue by rambaut** [beagle-dev/beagle-lib#159]
When using a BEAGLE installation made with the v3.1.2 MacOSX installer, newer OpenJDK java installations fail with a likely path issue:

```
Mar 21, 2021 12:53:26 PM beagle.BeagleFactory loadBeagleInstance
INFO:   BEAGLE function, create, returned error code -6 (No resource matches requirements)
Fatal exception: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
java.lang.RuntimeException: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
```

Installing BEAGLE from source works.

**Comment by msuchard** [comment]
We are preparing `v4_release` (separate branch) that uses `cmake` to generate Mac / Windows / linux installers.   It appears to work in my hands (without the error above).  Could you try that and report if `OpenJDK` is still problematic?

**Comment by anmh84** [comment]
I have the same problem：INFO:   BEAGLE function, create, returned error code -6 (No resource matches requirements)
Fatal exception: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
java.lang.RuntimeException: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
	at beagle.BeagleFactory.loadBeagleInstance(Unknown Source)
	at dr.evomodel.treedatalikelihood.BeagleDataLikelihoodDelegate.<init>(Unknown Source)
	at dr.evomodelxml.treedatalikelihood.TreeDataLikelihoodParser.createTreeDataLikelihood(Unknown Source)
	at dr.evomodelxml.treedatalikelihood.TreeDataLikelihoodParser.parseXMLObject(Unknown Source)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)

How to solve it ？Thank you
