### ISSUE TITLE
BEAGLE: No acceptable BEAGLE library plugins found on M1 Mac

### ISSUE THREAD

**Issue by bastiaanvdroest** [beagle-dev/beagle-lib#180]
Hi, 

I'm trying to run BEAST v1.10.4 with BEAGLE v3.0.0 installed (Java 8) on my Mac with m1 processor.
However, I get the following output:

Using BEAGLE DataLikelihood Delegate
Jul 25, 2022 1:40:46 PM beagle.BeagleFactory loadBeagleInstance
INFO:   BEAGLE function, create, returned error code -6 (No resource matches requirements)
Fatal exception: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
java.lang.RuntimeException: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
	at beagle.BeagleFactory.loadBeagleInstance(Unknown Source)
	at dr.evomodel.treedatalikelihood.BeagleDataLikelihoodDelegate.<init>(Unknown Source)
	at dr.evomodelxml.treedatalikelihood.TreeDataLikelihoodParser.createTreeDataLikelihood(Unknown Source)
	at dr.evomodelxml.treedatalikelihood.TreeDataLikelihoodParser.parseXMLObject(Unknown Source)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain
BEAST has terminated with an error.

I also tried it on another M1 Mac, but still get the same issue. Can you explain what is going wrong and how to fix this?

Kind regards,
Bastiaan

**Comment by longbow0** [comment]
Hi Bastiaan,

This error might because that the beagle-lib 3.x does not support the M1
arm64 CPU. The most recent beagle-lib 4.0.0 has solved this problem.

Please download beagle-lib 4.0.0 from:

https://github.com/beagle-dev/beagle-lib/releases

All the best
