### ISSUE TITLE
Error while executing BEAST through Singularity container

### ISSUE THREAD

**Issue by pehenrique** [beagle-dev/beagle-lib#209]
Hi all,

I'm trying to run a bayesian phylogeny using BEAST. I've downloaded the container and I was able to create the XML file using BEAUTI but when it comes to execute BEAST, it returns the following lines and I'm not sure how to solve it. Any help will be highly appreciated.

```
Using BEAGLE DataLikelihood Delegate
Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: [/usr/share/beast-mcmc, /usr/lib, /usr/lib//jni]
Fatal exception: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
java.lang.RuntimeException: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
	at beagle.BeagleFactory.loadBeagleInstance(Unknown Source)
	at dr.evomodel.treedatalikelihood.BeagleDataLikelihoodDelegate.<init>(Unknown Source)
	at dr.evomodelxml.treedatalikelihood.TreeDataLikelihoodParser.createTreeDataLikelihood(Unknown Source)
	at dr.evomodelxml.treedatalikelihood.TreeDataLikelihoodParser.parseXMLObject(Unknown Source)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
```

**Comment by xji3** [comment]
Hi @pehenrique, Could you share more details about your setup?  How did you install BEAGLE and how did you run BEAST xml? Do you see any beagle instances with `ls /usr/local/lib/*beagle*`?

**Comment by pehenrique** [comment]
Hi @xji3 

I've downloaded BEAST through singularity using the following line.

`$ singularity build beast.sif docker://biocontainers/beast-mcmc:v1.10.4dfsg-1-deb_cv1`

I execute the singularity container using the following line.

`$ singularity shell --bind /home/user/Documents/Pedro/:/home /home/user/sif_images/beast.sif`

Then I call beast and it returns the error:

```
Singularity> beast-mcmc teste_beast.xml 
/usr/bin/beast-mcmc: 26: /usr/bin/beast-mcmc: dpkg-architecture: not found
Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: [/usr/share/beast-mcmc, /usr/lib, /usr/lib//jni]
```

My setup is a laptop with Ubuntu 22.04.1 LTS, 64 GB RAM and a Intel i7-12700H.

About the beagle instances:

```
Singularity> ls /usr/local/lib/*beagle*
ls: cannot access '/usr/local/lib/*beagle*': No such file or directory
```

**Comment by xji3** [comment]
@pehenrique It looks like the singularity container that you used was last pushed 4 years ago ([docker container page](https://hub.docker.com/layers/biocontainers/beast-mcmc/v1.10.4dfsg-1-deb_cv1/images/sha256-a1be17dfd8ac93e4bb4b0e81e671a76d0517ede7429ca95b3f828b3a59fddc6c?context=explore)).
I would suggest you to remove it and install BEAGLE and BEAST following these instructions:

1. BEAGLE installation on Linux: [https://github.com/beagle-dev/beagle-lib/wiki/LinuxInstallInstructions](https://github.com/beagle-dev/beagle-lib/wiki/LinuxInstallInstructions)
2. BEAST installation on Linux: [https://beast.community/install_on_unix](https://beast.community/install_on_unix)

Please let me know if the problem persists.

**Comment by pehenrique** [comment]
@xji3 I'm trying to install using those instructions but when it comes to the step 2, I'm not sure if I'm doing correctly.

```
$git clone --depth=1 https://github.com/beagle-dev/beagle-lib.git
$cd beagle-lib
$mkdir build
$cd build
$cmake -DCMAKE_INSTALL_PREFIX:PATH=/build/ -DBUILD_JNI=OFF -DBUILD_CUDA=OFF -DBUILD_OPENCL=OFF

```
and that is the output:

```
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BEAGLE_VERSION = 4.0.1
-- BEAGLE_PLUGIN_VERSION = 40
-- Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
-- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED
-- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED - Success
-- Not using libtools for plugins
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/beagle-lib

```
Next step:

```
$make install

[  6%] Building CXX object libhmsbeagle/CMakeFiles/hmsbeagle.dir/beagle.cpp.o
[ 13%] Building CXX object libhmsbeagle/CMakeFiles/hmsbeagle.dir/benchmark/BeagleBenchmark.cpp.o
[ 20%] Building CXX object libhmsbeagle/CMakeFiles/hmsbeagle.dir/benchmark/linalg.cpp.o
[ 26%] Building CXX object libhmsbeagle/CMakeFiles/hmsbeagle.dir/plugin/Plugin.cpp.o
[ 33%] Building CXX object libhmsbeagle/CMakeFiles/hmsbeagle.dir/plugin/UnixSharedLibrary.cpp.o
[ 40%] Linking CXX shared library libhmsbeagle.so
[ 40%] Built target hmsbeagle
[ 46%] Building CXX object libhmsbeagle/CPU/CMakeFiles/hmsbeagle-cpu.dir/BeagleCPUPlugin.cpp.o
[ 53%] Linking CXX shared library libhmsbeagle-cpu.so
[ 53%] Built target hmsbeagle-cpu
[ 60%] Building CXX object libhmsbeagle/CPU/CMakeFiles/hmsbeagle-cpu-sse.dir/BeagleCPUSSEPlugin.cpp.o
In file included from /home/user/beagle-lib/libhmsbeagle/CPU/BeagleCPU4StateSSEImpl.h:338,
                 from /home/user/beagle-lib/libhmsbeagle/CPU/BeagleCPUSSEPlugin.cpp:9:
/home/user/beagle-lib/libhmsbeagle/CPU/BeagleCPU4StateSSEImpl.hpp: In member function ‘virtual void beagle::cpu::BeagleCPU4StateSSEImpl<double, T_PAD, P_PAD>::calcCrossProductsPartials(const double*, const double*, const double*, const double*, double, double*, double*)’:
/home/user/beagle-lib/libhmsbeagle/CPU/BeagleCPU4StateSSEImpl.hpp:563:25: warning: ignoring attributes on template argument ‘V_Real’ {aka ‘__m128d’} [-Wignored-attributes]
  563 |     std::array<V_Real, 8> vAcrossPatterns;
      |                         ^
/home/user/beagle-lib/libhmsbeagle/CPU/BeagleCPU4StateSSEImpl.hpp:566:25: warning: ignoring attributes on template argument ‘V_Real’ {aka ‘__m128d’} [-Wignored-attributes]
  566 |     std::array<V_Real, 8> vWithinPattern;
      |                         ^
[ 66%] Linking CXX shared library libhmsbeagle-cpu-sse.so
[ 66%] Built target hmsbeagle-cpu-sse
[ 73%] Building CXX object examples/CMakeFiles/hmctest.dir/hmctest/hmctest.cpp.o
[ 80%] Linking CXX executable hmctest
/usr/bin/ld: cannot open output file hmctest: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/hmctest.dir/build.make:100: examples/hmctest] Error 1
make[1]: *** [CMakeFiles/Makefile2:235: examples/CMakeFiles/hmctest.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

Then I set the environment variables putting the following command in the .bashrc file:
```
export LD_LIBRARY_PATH=/home/user/beagle-lib/libhmsbeagle:$LD_LIBRARY_PATH

export PKG_CONFIG_PATH=/lib/pkgconfig:$PKG_CONFIG_PATH
```

Finally, I run the final command:

```
$make test
Running tests...
Test project /home/user/beagle-lib
    Start 1: hmctest
Could not find executable hmctest
Looked in the following places:
hmctest
hmctest
Release/hmctest
Release/hmctest
Debug/hmctest
Debug/hmctest
MinSizeRel/hmctest
MinSizeRel/hmctest
RelWithDebInfo/hmctest
RelWithDebInfo/hmctest
Deployment/hmctest
Deployment/hmctest
Development/hmctest
Development/hmctest
Unable to find executable: hmctest
1/1 Test #1: hmctest ..........................***Not Run   0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.00 sec

The following tests FAILED:
	  1 - hmctest (Not Run)
Errors while running CTest
Output from these tests are in: /home/user/beagle-lib/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:91: test] Error 8

```

When it comes to run Beast, that's what I got:

`Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: [/home/user/Downloads/BEASTv1.10.4/lib, /usr/local/lib, /home/user/beagle-lib/libhmsbeagle, .]`

Any help will be highly appreciated. Thanks in advance.

**Comment by xji3** [comment]
@pehenrique the `cmake` command was wrong.  There are two dots at the end which refers to the parent directory for CMake to look for source code.  The correct one should look like this: `cmake -DCMAKE_INSTALL_PREFIX:PATH=/build/ -DBUILD_JNI=OFF -DBUILD_CUDA=OFF -DBUILD_OPENCL=OFF ..`

Please remove the `build` directory and start over again.

**Comment by pehenrique** [comment]
Hi @xji3 , I tried like you had instructed but I keep getting some errors.

First, with the cmake line, I tried this and everything works fine, including the "make test", but when I try to run BEAST, it returns an error and I think that's probably because I'm using the DBUILD_JNI=OFF?

```
$cmake -DCMAKE_INSTALL_PREFIX:PATH= .. -DBUILD_JNI=OFF -DBUILD_CUDA=OFF -DBUILD_OPENCL=OFF

Using BEAGLE DataLikelihood Delegate
Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: [/home/user/Downloads/BEASTv1.10.4/lib, /usr/local/lib, /home/user/beagle-lib/libhmsbeagle, /home/user/beagle-lib/libhmsbeagle, /home/user/beagle-lib/libhmsbeagle/, /home/user/beagle-lib/libhmsbeagle, .]
```

I also tried to locate the library as recommended (`$locate libhmsbeagle-jni.so`) but I didn't received any return.

If I try without the DBUILD_JNI parameters the cmake line don't work and I get this error:

```
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME ..
-- BEAGLE_VERSION = 4.0.1
-- BEAGLE_PLUGIN_VERSION = 40
-- Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
CMake Error at CMakeLists.txt:76 (message):
  No JNI includes and libraries found


-- Configuring incomplete, errors occurred!
See also "/home/user/beagle-lib/build/CMakeFiles/CMakeOutput.log".

```

If it helps, this is my java version:

```
$ java --version
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing)
```

**Comment by pehenrique** [comment]
Hi @xji3 , sorry for the inconvenience but I'm still struggling to run BEAST. With Beagle, everything works fine now, but I keep receiving the error message:

```
Using BEAGLE DataLikelihood Delegate
Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: [/home/user/Downloads/BEASTv1.10.4/lib, /usr/local/lib, /home/user/beagle-lib/libhmsbeagle, /home/user/beagle-lib/libhmsbeagle, /home/user/beagle-lib/libhmsbeagle/, /home/user/beagle-lib/libhmsbeagle, .]
```

When I use `$locate libhmsbeagle-jni.so` I don't receive any result.

Below is the steps that I follow to install Beagle, for me it worked and seems right, but I'm not sure.
```

$ cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME ..
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BEAGLE_VERSION = 4.0.1
-- BEAGLE_PLUGIN_VERSION = 40
-- Found JNI: /home/user/bin/Miniconda3/miniconda3/pkgs/openjdk-11.0.13-h87a67e3_0/lib/libjawt.so  
-- JAVA_HOME=/home/user/bin/Miniconda3/miniconda3/pkgs/openjdk-11.0.13-h87a67e3_0
-- JNI_INCLUDE_DIRS=/home/user/bin/Miniconda3/miniconda3/pkgs/openjdk-11.0.13-h87a67e3_0/include;/home/user/bin/Miniconda3/miniconda3/pkgs/openjdk-11.0.13-h87a67e3_0/include/linux;/home/user/bin/Miniconda3/miniconda3/pkgs/openjdk-11.0.13-h87a67e3_0/include
-- JNI_LIBRARIES=/home/user/bin/Miniconda3/miniconda3/pkgs/openjdk-11.0.13-h87a67e3_0/lib/libjawt.so;/home/user/bin/Miniconda3/miniconda3/pkgs/openjdk-11.0.13-h87a67e3_0/lib/server/libjvm.so
-- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED
-- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED - Success
-- Not using libtools for plugins
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/beagle-lib/build

$ make install
[  5%] Building CXX object libhmsbeagle/CMakeFiles/hmsbeagle.dir/beagle.cpp.o
[ 11%] Building CXX object libhmsbeagle/CMakeFiles/hmsbeagle.dir/benchmark/BeagleBenchmark.cpp.o
[ 17%] Building CXX object libhmsbeagle/CMakeFiles/hmsbeagle.dir/benchmark/linalg.cpp.o
[ 23%] Building CXX object libhmsbeagle/CMakeFiles/hmsbeagle.dir/plugin/Plugin.cpp.o
[ 29%] Building CXX object libhmsbeagle/CMakeFiles/hmsbeagle.dir/plugin/UnixSharedLibrary.cpp.o
[ 35%] Linking CXX shared library libhmsbeagle.so
[ 35%] Built target hmsbeagle
[ 41%] Building CXX object libhmsbeagle/CPU/CMakeFiles/hmsbeagle-cpu.dir/BeagleCPUPlugin.cpp.o
[ 47%] Linking CXX shared library libhmsbeagle-cpu.so
[ 47%] Built target hmsbeagle-cpu
[ 52%] Building CXX object libhmsbeagle/CPU/CMakeFiles/hmsbeagle-cpu-sse.dir/BeagleCPUSSEPlugin.cpp.o
In file included from /home/user/beagle-lib/libhmsbeagle/CPU/BeagleCPU4StateSSEImpl.h:338,
                 from /home/user/beagle-lib/libhmsbeagle/CPU/BeagleCPUSSEPlugin.cpp:9:
/home/user/beagle-lib/libhmsbeagle/CPU/BeagleCPU4StateSSEImpl.hpp: In member function ‘virtual void beagle::cpu::BeagleCPU4StateSSEImpl<double, T_PAD, P_PAD>::calcCrossProductsPartials(const double*, const double*, const double*, const double*, double, double*, double*)’:
/home/user/beagle-lib/libhmsbeagle/CPU/BeagleCPU4StateSSEImpl.hpp:563:25: warning: ignoring attributes on template argument ‘V_Real’ {aka ‘__m128d’} [-Wignored-attributes]
  563 |     std::array<V_Real, 8> vAcrossPatterns;
      |                         ^
/home/user/beagle-lib/libhmsbeagle/CPU/BeagleCPU4StateSSEImpl.hpp:566:25: warning: ignoring attributes on template argument ‘V_Real’ {aka ‘__m128d’} [-Wignored-attributes]
  566 |     std::array<V_Real, 8> vWithinPattern;
      |                         ^
[ 58%] Linking CXX shared library libhmsbeagle-cpu-sse.so
[ 58%] Built target hmsbeagle-cpu-sse
[ 64%] Building CXX object libhmsbeagle/JNI/CMakeFiles/hmsbeagle-jni.dir/beagle_BeagleJNIWrapper.cpp.o
[ 70%] Linking CXX shared library libhmsbeagle-jni.so
[ 70%] Built target hmsbeagle-jni
[ 76%] Building CXX object examples/CMakeFiles/hmctest.dir/hmctest/hmctest.cpp.o
[ 82%] Linking CXX executable hmctest
[ 82%] Built target hmctest
[ 88%] Building CXX object examples/CMakeFiles/synthetictest.dir/synthetictest/synthetictest.cpp.o
[ 94%] Building CXX object examples/CMakeFiles/synthetictest.dir/synthetictest/linalg.cpp.o
[100%] Linking CXX executable synthetictest
[100%] Built target synthetictest
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /home/user/lib/libhmsbeagle.so.1
-- Set runtime path of "/home/user/lib/libhmsbeagle.so.1" to ""
-- Up-to-date: /home/user/lib/libhmsbeagle.so
-- Installing: /home/user/include/libhmsbeagle-1/libhmsbeagle/beagle.h
-- Installing: /home/user/include/libhmsbeagle-1/libhmsbeagle/platform.h
-- Installing: /home/user/lib/cmake/hmsbeagle-1/hmsbeagle-1Config.cmake
-- Installing: /home/user/lib/cmake/hmsbeagle-1/hmsbeagle-1Config-relwithdebinfo.cmake
-- Installing: /home/user/lib/cmake/hmsbeagle-1/hmsbeagle-1ConfigVersion.cmake
-- Installing: /home/user/lib/pkg-config/hmsbeagle-1.pc
-- Installing: /home/user/lib/libhmsbeagle-cpu.so.40.0.0
-- Up-to-date: /home/user/lib/libhmsbeagle-cpu.so
-- Installing: /home/user/lib/libhmsbeagle-cpu-sse.so.40.0.0
-- Up-to-date: /home/user/lib/libhmsbeagle-cpu-sse.so
-- Installing: /home/user/lib/libhmsbeagle-jni.so
-- Set runtime path of "/home/user/lib/libhmsbeagle-jni.so" to ""

$ make test
Running tests...
Test project /home/user/beagle-lib/build
    Start 1: hmctest
1/1 Test #1: hmctest ..........................   Passed    0.00 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.00 sec
```
The folder where Beagle is:

```
$ ls beagle-lib/build/libhmsbeagle/
CMakeFiles  cmake_install.cmake  CPU  GPU  hmsbeagle-1ConfigVersion.cmake  hmsbeagle-1.pc  JNI  libhmsbeagle.so  libhmsbeagle.so.1  Makefile
$ ls beagle-lib/libhmsbeagle/
beagle.cpp  beagle.h  BeagleImpl.h  benchmark  CMakeLists.txt  CPU  GPU  hmsbeagle-1.pc.in  JNI  platform.h  plugin
```

If I try to run Beast using the full path:

```
$java -jar -Djava.libary.path=/home/user/beagle-lib/ -jar ./Downloads/BEASTv1.10.4/lib/beast.jar
$java -jar -Djava.libary.path=/home/user/beagle-lib/build/libhmsbeagle/ -jar ./Downloads/BEASTv1.10.4/lib/beast.jar
$ java -jar -Djava.libary.path=/home/user/beagle-lib/libhmsbeagle/ -jar ./Downloads/BEASTv1.10.4/lib/beast.jar

```
Any of those lines don't work.

If I look in the folders otherwise, I can see the jni.so library:

```
$ ls beagle-lib/build/libhmsbeagle/JNI/
CMakeFiles  cmake_install.cmake  libhmsbeagle-jni.so  Makefile
```

Thanks in advance.

**Comment by xji3** [comment]
@pehenrique Happy to hear that.  Congratulations.
